import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ModeSelector from "./ConfigSelector";
import StoreProvider from "./StoreProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Plotting test",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <StoreProvider>
            <html lang="en">
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased flex w-screen h-screen`}
                >
                    <nav className="p-4 bg-gray-100 w-fit">
                        <h1 className="mb-2 text-2xl font-bold text-black">Plotting Playground</h1>
                        <p><a className="text-black hover:text-blue-500 transition-colors duration-100" href="./chartjs">Chart.js</a></p>
                        <p><a className="text-black hover:text-blue-500 transition-colors duration-100" href="./plotly">Plotly</a></p>
                        <p><a className="text-black hover:text-blue-500 transition-colors duration-100" href="./observable">Observable</a></p>
                    </nav>
                    <main className="flex-1 flex flex-col">
                        <ModeSelector />
                        <div className="p-4 w-full flex-1 bg-white">
                            {children}
                        </div>
                    </main>
                </body>
            </html>
        </StoreProvider>

    );
}
